name: Pull Request Checks
on:
  pull_request:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Perform check build
        run: make docker-build
      - name: Run tests
        run: make test